### ISSUE TITLE
Board freezes after a few minutes. No logs appear from button press

### ISSUE THREAD

**Issue by nherriot** [rzr/webthing-iotjs#2]
After flashing a fresh image and setting up WiFi the board boots properly.
However the log message that appears when pressing the test buttons that should put out a log:

TASH>>\0x00log: GPIO: LeftButton: change: false
log: GPIO: LeftButton: change: true
log: GPIO: RightButton: change: false
log: GPIO: RightButton: change: true

no longer work after about 5 minutes.
There is also no command processing in the shell. i.e. when you type TASH>> help 
you should get a list of commands that can by used. On my terminal emulator 'cutecom' there is nothing being produced by the logs.
There is a 'bad sync' error that seems to appear:

U-Boot 2017.01-g59977f7 (Nov 23 2017 - 16:09:49 +0900)

CPU:   Exynos200 @ 320 MHz
Model: ARTIK-053 based on Exynos T20
DRAM:  946 KiB
WARNING: Caches not enabled
BL1 released at 2017-3-13 15:00
SSS released at 2017-09-12
WLAN released at 2017-11-30
Flash: 8 MiB
*** Warning - bad CRC, using default environment

In:    serial@80180000
Out:   serial@80180000
Err:   serial@80180000
Hit any key to stop autoboot:  0 
gpio: pin gpg16 (gpio 46) value is 1
## Starting application at 0x040C\0xb8020 ...
s5j_sflash_init: FLASH Quad Enabled
uart_register: Registering /dev/console
uart_register: Registering /dev/ttyS0
uart_register: Registering /dev/ttyS1
uart_register: Registering /dev/ttyS2
uart_register: Registering /dev/ttyS3
uart_register: Registering /dev/ttyS4
System Information:
\0x09Version: 2.0
\0x09Commit Hash: eec74f072c1dd16c9713862850bc5ff3393e5209
\0x09Build User: nherriot@Zenbook-UX32A
\0x09Build Time: 2018-10-09 15:53:51
\0x09System Time: 01 Jan 2010, 00:00:00 [s] UTC Hardware RTC Support
TASH>>\0x00log: iotjs_startup_wifi_connect
log: Connecting to SSID "srbackup" (4+5)
log: Wait (1/3) sec...
i2c_uioregister: Registering /dev/i2c-0
i2c_uioregister: Registering /dev/i2c-1
log: Wait (2/3) sec...
log: Wait (3/3) sec...
[WM] T7 _handle_request:1334 state(0) evt(0)
[WM] T7 _handler_on_uninitialized_state:887 state(0) evt(0)
Starting supplicant in foreground...
1262304003.123427: Successfully initialized wpa_supplicant
1262304006.206938: wl1: callling L2_packet_init: 
1262304006.206938: wl1: Own MAC address: 28:6d:97:40:15:96
[WM] T7 <-- _handle_request
[WM] T7 _handle_request:1334 state(1) evt(4)
[WM] T7 _handler_on_disconnected_state:943 state(1) evt(4)
[WM] T7\0x09_wifimgr_connect_ap:744
[WM] T7\0x09_wifimgr_save_connected_config:733
[WM] T7 <-- _handle_request
1262304008.142864: wl1: Associated with 0c:68:03:ca:46:e7
1262304008.162822: wl1: WPA: Key negotiation completed with 0c:68:03:ca:46:e7 [PTK=CCMP GTK=CCMP]
1262304008.162822: wl1: CTRL-EVENT-CONNECTED 
[WM] T12\0x09_wifi_utils_connect_event:834
[WM] T12 _handle_request:1334 state(3) evt(9)
[WM] T12 _handler_on_connecting_state:1011 state(3) evt(9)
[WM] IP address : 192.168.110.197 ----
[WM] T12\0x09_handle_user_cb:1269
[WM] call sta connect success event
log: iotjs_startup_wifi_sta_connected status=0x0
[WM] T12 <-- _handle_request
log: IoT.js app: Starting:
{
  "env": {
    "HOME": "",
    "IOTJS_PATH": "/rom",
    "IOTJS_ENV": "",
    "IOTJS_EXTRA_MODULE_PATH": "",
    "IOTJS_WORKING_DIR_PATH": ""
  },
  "builtin_modules": {
    "adc": true,
    "assert": true,
    "buffer": true,
    "console": true,
    "dgram": true,
    "dns": true,
    "events": true,
    "fs": true,
    "gpio": true,
    "http": true,
    "http_client": true,
    "http_common": true,
    "http_incoming": true,
    "http_outgoing": true,
    "http_server": true,
    "https": true,
    "i2c": true,
    "iotjs": true,
    "module": true,
    "net": true,
    "pwm": true,
    "spi": true,
    "stream": true,
    "stream_duplex": true,
    "stream_internal": true,
    "stream_readable": true,
    "stream_writable": true,
    "timers": true,
    "tls": true,
    "uart": true,
    "util": true,
    "constants": true,
    "http_parser": true,
    "process": true,
    "tcp": true,
    "udp": true
  },
  "platform": "tizenrt",
  "arch": "arm",
  "version": "1.0.0",
  "iotjs": {
    "board": "artik05x"
  },
  "argv": [
    "iotjs",
    "/rom/example/index.js"
  ],
  "_events": {},
  "exitCode": 0,
  "_exiting": false
}
log: IoT.js app: Loading: /rom/iotjs-modules/webthing-iotjs/example/platform/index.js
log: board: artik05x: Loading
Usage:
iotjs /rom/example/index.js [board] [port]
Try:
curl -H "Accept: application/json" http://localhost:8888

log: board: artik05x: Started
log: GPIO: BlueLed: open: null
log: GPIO: RedLed: open: null
log: GPIO: LeftButton: open: null (null expected)
log: GPIO: RightButton: open: null (null expected)
log: ADC: ADC1: open: null (null expected)
log: ADC: ADC2: open: null (null expected)
log: GPIO: LeftButton: change: true
log: GPIO: RightButton: change: true
log: ADC: ADC1: change: 0%
log: ADC: ADC2: change: 0%
help
\0x09 TASH command list 
\0x09 --------------------
cat              cd               date             df               
dhcpd            echo             exit             free             
getenv           heapinfo         hello            help             
ifconfig         ifdown           ifup             iotjs            
iotjs_startup    iperf            kill             killall          
logm             ls               mkdir            mkrd             
mksmartfs        mount            netmon           ping             
ps               pwd              ramtest          reboot           
rm               rmdir            setenv           sleep            
stkmon           umount           unsetenv         uptime           
wifi             
TASH>>\0x00
TASH>>\0x00log: GPIO: LeftButton: change: false
log: GPIO: LeftButton: change: true
log: GPIO: RightButton: change: false
log: GPIO: RightButton: change: true
input_irq_handler: input_irq_handler: Bad sync in header: header=0x96690002
input_irq_handler: input_irq_handler: Bad sync in header: header=0x05b0bc8c
input_irq_handler: input_irq_handler: Bad sync in header: header=0x00000a8f

**Comment by rzr** [comment]
You should not setup wifi after flashing, can you also test gpio output (LEDs) and see if we have the same trace about:
```
 input_irq_handler: input_irq_handler: Bad sync in header: header=0x96690002
```

**Comment by rzr** [comment]
Hi,
Any progress on this ?

I am not able to reproduce (it worked the whole night.) , but I can try to help to narrow your problem with a couple of hints:

1st, just let it run, if you stressing the system randomly it will create confusion and we need to ensure you are able to reproduce at least my run session

2d let's make sure we are using the same env, I can prepare a docker script to make sure we're building on the same setup (but I have low expectation this is the root cause)

3d, Let's disable wifi to make sure it's not related

4d, you can try on other boards if you have others and repeat the exact same steps (note times of events) 

5, document the simplest test case and share commented logs here

**Comment by nherriot** [comment]
SLAP!
Yes love to. You available Sat/Sun? I'm really under pressure to get all the other parts configured up and running, simply did not expect the effort required to try and run WoT on the platform. I'm dropping Tizen from the demo - far too risky since I'm not a Tizen developer or expert!
Once I have everything else fully working - I'll switch back to Tizen.

**Comment by rzr** [comment]
Ok I'll try to be around, let's keep this open if anyone else is facing similar issues

**Comment by rzr** [comment]
Try with the branch:
https://github.com/TizenTeam/TizenRT/tree/sandbox/rzr/devel/artik/055s/master

Make sure to overload with: machine=artik053 or other

There is also a dockerfile in, I use it as:

```sh
    app="webthing-iotjs"
    machine="artik055s" # TODO: Update for other artik05x boards
    name="${USER}/tizenrt-${app}-${machine}"
    docker stop ${name} ||:
    docker rm ${name} ||:
    docker build -t ${name} --build-arg "app=${app}" .
    # Unplug and replug board on USB
    docker run --privileged --rm -ti "${name}" -C "rules/${app}" demo  machine="$machine" # tty=/dev/ttyUSB1
    docker stop ${name}
```

Good luck, please confirm different behaviour on differents boards

**Comment by ziransun** [comment]
Start fine for me after pressed "reset" button.  
********************
BL1 released at 2017-3-13 15:00
SSS released at 2017-09-12
WLAN released at 2017-03-21
Flash: 8 MiB
*** Warning - bad CRC, using default environment

In:    serial@80180000
Out:   serial@80180000
Err:   serial@80180000
Hit any key to stop autoboot:  0 
gpio: pin gpg16 (gpio 46) value is 1
## Starting application at 0x040C8020 ...
s5j_sflash_init: FLASH Quad Enabled
i2c_uioregister: Registering /dev/i2c-0
i2c_uioregister: Registering /dev/i2c-1
System Information:
        Version: 2.0
        Commit Hash: 8e305aa0dadac955bdb9781b6631b7036762b152
        Build User: z.sun@nb-974
        Build Time: 2018-10-18 13:43:57
        System Time: 01 Jan 2010, 00:00:00 [s] UTC Hardware RTC Support
TASH>>log: iotjs_startup_wifi_connect
1262304006.226896: wl1: callling L2_packet_init: 
1262304006.226896: wl1: Own MAC address: 28:6d:97:41:24:44
[WM] T6 <-- _handle_request
[WM] T6 _handle_request:1334 state(1) evt(4)
[WM] T6 _handler_on_disconnected_state:943 state(1) evt(4)
[WM] T6 _wifimgr_connect_ap:744ed_state:887 state(0) evt(0)
connect ap failcant in foreground...
[WM] T6 <-- _handle_requestully initialized wpa_supplicant
error: wifi_manager_connect_ap (status=0xffffffff)
***************************

**Comment by rzr** [comment]
Isnt @ziransun comment related to:
https://github.com/rzr/webthing-iotjs/issues/1

please confirm if board is frozen or not

**Comment by rzr** [comment]
Any idea how to reproduce this error:

    input_irq_handler: input_irq_handler: Bad sync in header: header=

I see it's also reported elsewhere:

https://developer.artik.io/forums/t/artik-sdk-examples-and-ota-artik-055s/7403/1

**Comment by rzr** [comment]
It looks like this issue is specific to ARTIK053, when WiFi is enabled on boot,
without wifi i managed to make it run all night long...

@nherriot please confirm ARTIK055s is working as expected and then rename the bug title

I'll try to narrow the config options

**Comment by nherriot** [comment]
Tested on Artik055, this change does not interfere with the Artik055 board.
