### ISSUE TITLE
STM32 support is missing

### ISSUE THREAD

**Issue by michaesc** [rzr/webthing-iotjs#3]
Our financial instruments use STM32F (and we're trying to integrate STM32L.) The secure signing devices would benefit from this framework, but it is not supported on any STM32 MCU.

Please port IoT WoT to the STM32 (for example STM32F205RET6.)

**Comment by michaesc** [comment]
As an example of our Opensource project using STM32F405RGT6 and similar, please refer to:

https://github.com/monero-project/kastelo/blob/revstm/hardware/breakneck/schematic/breakneck.pdf

**Comment by rzr** [comment]
Hi @michaesc thx for suggesting new hw support.

STM32 is good target too I have considered it, but I lack a device with connectivity, I think the IoT devboard could be a good candidate.

Then I know that STM32F4 was or is still supported by iotjs using Nuttx OS:
https://github.com/Samsung/iotjs/wiki/Build-for-STM32F4-NuttX

Meanwhile, I only have a STM32F3 (without connectivity) but  IIRC it also supports NuttX, that could worth a try.

**Comment by rzr** [comment]
FYI, I can share some experiments for STM32F4 using nuttx it's booting  shell is appearing fine but not when linked to iotjs... more investigation will be needed, ping me if any interest, I will clean up this draft helper project:

https://github.com/rzr/rzr-wip/tree/sandbox/rzr/nuttx/devel/master

cc: @Jorgininho

**Comment by rzr** [comment]
Hints, Feedback and status update welcome at:

https://github.com/rzr/webthing-iotjs/wiki/MCU

**Comment by rzr** [comment]
Hi,
Are there any internet on this? 

FYI, I have basic iotjs support. but http is not working properly yet so more investigation will be needed.

Maybe it could be simpler to bring support to this project first:
https://github.com/SamsungInternet/iotjs-express

**Comment by rzr** [comment]
Updates here,

FYI I just managed to get webthing-iotjs working on "Nucleo-f767ZI" 
using NuttX flavor or IoT.js.

Until it's fully unstreamed I can explain how to use it, just ask me to explain more on this page:
https://github.com/rzr/webthing-iotjs/wiki/MCU#

Then I'll have to add PWM support, to be tracked at:
https://bitbucket.org/nuttx/nuttx/issues/153/crash-on-mm_takesemaphore-in-pwm_register#

And in longer term this could be ported to TizenRT too, if anybody want to join doing this ?

Cc: @jzorjnz, @fpistm

**Comment by fpistm** [comment]
Hi @rzr 
what did you expect from me here ?
Sorry, I'm not familiar with webthing-iotjs :sweat_smile:

**Comment by rzr** [comment]
Nothing special, just wanted to let you know as you already merged my patches ;)

For your info webthings (http rest devices) can be implemented using arduino API (using stm32duino) or with plain javascript using IoT.js which is based on JerryScript (also used by mbed + @jzorjnz modules)

Relate-to: https://github.com/stm32duino/STM32Ethernet/pull/17

Stay tuned,

https://social.samsunginter.net/@rzr/100882359240971661#web-of-things-agriculture-20180712rzr#

**Comment by fpistm** [comment]
@rzr 
Ok fine ;)
Thanks for the link, I will try to go further on this.

**Comment by rzr** [comment]
Relate-to: https://github.com/pando-project/jerryscript/pull/2838

**Comment by rzr** [comment]
Update: https://purl.org/rzr/digitaltwins-webthings-iotjs-20190512rzr# 

I'll have to upstream a couple of fixes and then close this issue.

**Comment by rzr** [comment]
STM32 support is provided with Nucleof767ZI see sample webthing:

* https://github.com/rzr/webthing-iotjs/blob/master/example/platform/board/nucleo-f767zi.js
* https://github.com/rzr/webthing-iotjs/commit/e86dbea35b4537924b1a988543906dcb1c98fb75

[![Nucleof767ZI](https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/socialsamsunginternet/media_attachments/files/000/015/225/original/0d874cce3c8913dd.png)](https://social.samsunginter.net/@rzr/102350213105279661#Nucleof767ZI# "Nucleof767ZI")

Released in:

* https://github.com/rzr/webthing-iotjs/tree/webthing-iotjs-0.11.2-1
* https://www.npmjs.com/package/webthing-iotjs/v/0.11.2-1


I am closing this issue, please open new bugs for related issues or wishes

A couple of suggestion here: rebase on TizenRT, support BLE, target more boards.

More more detail to come at :

https://github.com/rzr/webthing-iotjs/wiki/MCU

Thanks for your patience

**Comment by rzr** [comment]
Are there any other STM32 boards to be considered ?

STM32MP1 should easy to port using:

https://github.com/STMicroelectronics/meta-st-stm32mp/commits/zeus

Please let me know at:

https://community.st.com/s/feed/0D50X0000ArV5ykSQC

Regards
